//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace DongBo_CContract.service_hoadon {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="service_ketnoiSoap", Namespace="http://tempuri.org/")]
    public partial class service_ketnoi : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback Fs_SERVICE_HD_NHOperationCompleted;
        
        private System.Threading.SendOrPostCallback Fs_IV_MAP_NHOperationCompleted;
        
        private System.Threading.SendOrPostCallback Fs_SERVICE_NH_KYOperationCompleted;
        
        private System.Threading.SendOrPostCallback Fs_SERVICE_NHOperationCompleted;
        
        private System.Threading.SendOrPostCallback Fs_SERVICE_INVOICE_NHOperationCompleted;
        
        private System.Threading.SendOrPostCallback Fs_SERVICE_INVOICE_MUTI_NHOperationCompleted;
        
        private System.Threading.SendOrPostCallback Fs_SERVICE_INVOICE_INOperationCompleted;
        
        private System.Threading.SendOrPostCallback Fs_SERVICE_INVOICE_IN_FKEYOperationCompleted;
        
        private System.Threading.SendOrPostCallback Fs_SERVICE_INVOICE_HUYOperationCompleted;
        
        private System.Threading.SendOrPostCallback Fs_SERVICE_INVOICE_HUY_FKEYOperationCompleted;
        
        private System.Threading.SendOrPostCallback Fs_SERVICE_INVOICE_CTOperationCompleted;
        
        private System.Threading.SendOrPostCallback Fs_USER_TTOperationCompleted;
        
        private System.Threading.SendOrPostCallback Fs_IV_MA_FKEYOperationCompleted;
        
        private System.Threading.SendOrPostCallback Fs_SERVICE_INVOICE_KEY_CTOperationCompleted;
        
        private System.Threading.SendOrPostCallback Fs_SERVICE_INVOICE_KEY_CT_XMLOperationCompleted;
        
        private System.Threading.SendOrPostCallback Fs_SERVICE_IMPORT_DENSOOperationCompleted;
        
        private System.Threading.SendOrPostCallback Fs_LoadListMauOperationCompleted;
        
        private System.Threading.SendOrPostCallback Fs_LoadListSeriOperationCompleted;
        
        private System.Threading.SendOrPostCallback Fs_SERVICE_KY_SERVEROperationCompleted;
        
        private System.Threading.SendOrPostCallback Fs_SERVICE_KY_MUTIL_SERVEROperationCompleted;
        
        private System.Threading.SendOrPostCallback Fs_DN_CTOperationCompleted;
        
        private System.Threading.SendOrPostCallback TOOL_SENDMAILOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public service_ketnoi() {
            this.Url = global::DongBo_CContract.Properties.Settings.Default.Solomon_Invoice_service_hoadon_service_ketnoi;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event Fs_SERVICE_HD_NHCompletedEventHandler Fs_SERVICE_HD_NHCompleted;
        
        /// <remarks/>
        public event Fs_IV_MAP_NHCompletedEventHandler Fs_IV_MAP_NHCompleted;
        
        /// <remarks/>
        public event Fs_SERVICE_NH_KYCompletedEventHandler Fs_SERVICE_NH_KYCompleted;
        
        /// <remarks/>
        public event Fs_SERVICE_NHCompletedEventHandler Fs_SERVICE_NHCompleted;
        
        /// <remarks/>
        public event Fs_SERVICE_INVOICE_NHCompletedEventHandler Fs_SERVICE_INVOICE_NHCompleted;
        
        /// <remarks/>
        public event Fs_SERVICE_INVOICE_MUTI_NHCompletedEventHandler Fs_SERVICE_INVOICE_MUTI_NHCompleted;
        
        /// <remarks/>
        public event Fs_SERVICE_INVOICE_INCompletedEventHandler Fs_SERVICE_INVOICE_INCompleted;
        
        /// <remarks/>
        public event Fs_SERVICE_INVOICE_IN_FKEYCompletedEventHandler Fs_SERVICE_INVOICE_IN_FKEYCompleted;
        
        /// <remarks/>
        public event Fs_SERVICE_INVOICE_HUYCompletedEventHandler Fs_SERVICE_INVOICE_HUYCompleted;
        
        /// <remarks/>
        public event Fs_SERVICE_INVOICE_HUY_FKEYCompletedEventHandler Fs_SERVICE_INVOICE_HUY_FKEYCompleted;
        
        /// <remarks/>
        public event Fs_SERVICE_INVOICE_CTCompletedEventHandler Fs_SERVICE_INVOICE_CTCompleted;
        
        /// <remarks/>
        public event Fs_USER_TTCompletedEventHandler Fs_USER_TTCompleted;
        
        /// <remarks/>
        public event Fs_IV_MA_FKEYCompletedEventHandler Fs_IV_MA_FKEYCompleted;
        
        /// <remarks/>
        public event Fs_SERVICE_INVOICE_KEY_CTCompletedEventHandler Fs_SERVICE_INVOICE_KEY_CTCompleted;
        
        /// <remarks/>
        public event Fs_SERVICE_INVOICE_KEY_CT_XMLCompletedEventHandler Fs_SERVICE_INVOICE_KEY_CT_XMLCompleted;
        
        /// <remarks/>
        public event Fs_SERVICE_IMPORT_DENSOCompletedEventHandler Fs_SERVICE_IMPORT_DENSOCompleted;
        
        /// <remarks/>
        public event Fs_LoadListMauCompletedEventHandler Fs_LoadListMauCompleted;
        
        /// <remarks/>
        public event Fs_LoadListSeriCompletedEventHandler Fs_LoadListSeriCompleted;
        
        /// <remarks/>
        public event Fs_SERVICE_KY_SERVERCompletedEventHandler Fs_SERVICE_KY_SERVERCompleted;
        
        /// <remarks/>
        public event Fs_SERVICE_KY_MUTIL_SERVERCompletedEventHandler Fs_SERVICE_KY_MUTIL_SERVERCompleted;
        
        /// <remarks/>
        public event Fs_DN_CTCompletedEventHandler Fs_DN_CTCompleted;
        
        /// <remarks/>
        public event TOOL_SENDMAILCompletedEventHandler TOOL_SENDMAILCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Fs_SERVICE_HD_NH", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Fs_SERVICE_HD_NH(string b_nsd, string b_mk, string b_loai, string b_so_id, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] hoadon_gtgt hoadon, hoadon_gtgt_ct[] hoadon_ct, string b_ktra_dch) {
            object[] results = this.Invoke("Fs_SERVICE_HD_NH", new object[] {
                        b_nsd,
                        b_mk,
                        b_loai,
                        b_so_id,
                        hoadon,
                        hoadon_ct,
                        b_ktra_dch});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Fs_SERVICE_HD_NHAsync(string b_nsd, string b_mk, string b_loai, string b_so_id, hoadon_gtgt hoadon, hoadon_gtgt_ct[] hoadon_ct, string b_ktra_dch) {
            this.Fs_SERVICE_HD_NHAsync(b_nsd, b_mk, b_loai, b_so_id, hoadon, hoadon_ct, b_ktra_dch, null);
        }
        
        /// <remarks/>
        public void Fs_SERVICE_HD_NHAsync(string b_nsd, string b_mk, string b_loai, string b_so_id, hoadon_gtgt hoadon, hoadon_gtgt_ct[] hoadon_ct, string b_ktra_dch, object userState) {
            if ((this.Fs_SERVICE_HD_NHOperationCompleted == null)) {
                this.Fs_SERVICE_HD_NHOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFs_SERVICE_HD_NHOperationCompleted);
            }
            this.InvokeAsync("Fs_SERVICE_HD_NH", new object[] {
                        b_nsd,
                        b_mk,
                        b_loai,
                        b_so_id,
                        hoadon,
                        hoadon_ct,
                        b_ktra_dch}, this.Fs_SERVICE_HD_NHOperationCompleted, userState);
        }
        
        private void OnFs_SERVICE_HD_NHOperationCompleted(object arg) {
            if ((this.Fs_SERVICE_HD_NHCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Fs_SERVICE_HD_NHCompleted(this, new Fs_SERVICE_HD_NHCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Fs_IV_MAP_NH", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Fs_IV_MAP_NH(string b_nsd, string b_mk, string b_so_id, string b_fkey) {
            object[] results = this.Invoke("Fs_IV_MAP_NH", new object[] {
                        b_nsd,
                        b_mk,
                        b_so_id,
                        b_fkey});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Fs_IV_MAP_NHAsync(string b_nsd, string b_mk, string b_so_id, string b_fkey) {
            this.Fs_IV_MAP_NHAsync(b_nsd, b_mk, b_so_id, b_fkey, null);
        }
        
        /// <remarks/>
        public void Fs_IV_MAP_NHAsync(string b_nsd, string b_mk, string b_so_id, string b_fkey, object userState) {
            if ((this.Fs_IV_MAP_NHOperationCompleted == null)) {
                this.Fs_IV_MAP_NHOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFs_IV_MAP_NHOperationCompleted);
            }
            this.InvokeAsync("Fs_IV_MAP_NH", new object[] {
                        b_nsd,
                        b_mk,
                        b_so_id,
                        b_fkey}, this.Fs_IV_MAP_NHOperationCompleted, userState);
        }
        
        private void OnFs_IV_MAP_NHOperationCompleted(object arg) {
            if ((this.Fs_IV_MAP_NHCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Fs_IV_MAP_NHCompleted(this, new Fs_IV_MAP_NHCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Fs_SERVICE_NH_KY", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Fs_SERVICE_NH_KY(string b_nsd, string b_mk, string b_loai, string b_so_id, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] hoadon_gtgt hoadon, hoadon_gtgt_ct[] hoadon_ct, string b_ktra_dch) {
            object[] results = this.Invoke("Fs_SERVICE_NH_KY", new object[] {
                        b_nsd,
                        b_mk,
                        b_loai,
                        b_so_id,
                        hoadon,
                        hoadon_ct,
                        b_ktra_dch});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Fs_SERVICE_NH_KYAsync(string b_nsd, string b_mk, string b_loai, string b_so_id, hoadon_gtgt hoadon, hoadon_gtgt_ct[] hoadon_ct, string b_ktra_dch) {
            this.Fs_SERVICE_NH_KYAsync(b_nsd, b_mk, b_loai, b_so_id, hoadon, hoadon_ct, b_ktra_dch, null);
        }
        
        /// <remarks/>
        public void Fs_SERVICE_NH_KYAsync(string b_nsd, string b_mk, string b_loai, string b_so_id, hoadon_gtgt hoadon, hoadon_gtgt_ct[] hoadon_ct, string b_ktra_dch, object userState) {
            if ((this.Fs_SERVICE_NH_KYOperationCompleted == null)) {
                this.Fs_SERVICE_NH_KYOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFs_SERVICE_NH_KYOperationCompleted);
            }
            this.InvokeAsync("Fs_SERVICE_NH_KY", new object[] {
                        b_nsd,
                        b_mk,
                        b_loai,
                        b_so_id,
                        hoadon,
                        hoadon_ct,
                        b_ktra_dch}, this.Fs_SERVICE_NH_KYOperationCompleted, userState);
        }
        
        private void OnFs_SERVICE_NH_KYOperationCompleted(object arg) {
            if ((this.Fs_SERVICE_NH_KYCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Fs_SERVICE_NH_KYCompleted(this, new Fs_SERVICE_NH_KYCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Fs_SERVICE_NH", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Fs_SERVICE_NH(string b_nsd, string b_mk, string b_loai, string b_so_id, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] hoadon_gtgt hoadon, hoadon_gtgt_ct[] hoadon_ct, string b_ktra_dch) {
            object[] results = this.Invoke("Fs_SERVICE_NH", new object[] {
                        b_nsd,
                        b_mk,
                        b_loai,
                        b_so_id,
                        hoadon,
                        hoadon_ct,
                        b_ktra_dch});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Fs_SERVICE_NHAsync(string b_nsd, string b_mk, string b_loai, string b_so_id, hoadon_gtgt hoadon, hoadon_gtgt_ct[] hoadon_ct, string b_ktra_dch) {
            this.Fs_SERVICE_NHAsync(b_nsd, b_mk, b_loai, b_so_id, hoadon, hoadon_ct, b_ktra_dch, null);
        }
        
        /// <remarks/>
        public void Fs_SERVICE_NHAsync(string b_nsd, string b_mk, string b_loai, string b_so_id, hoadon_gtgt hoadon, hoadon_gtgt_ct[] hoadon_ct, string b_ktra_dch, object userState) {
            if ((this.Fs_SERVICE_NHOperationCompleted == null)) {
                this.Fs_SERVICE_NHOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFs_SERVICE_NHOperationCompleted);
            }
            this.InvokeAsync("Fs_SERVICE_NH", new object[] {
                        b_nsd,
                        b_mk,
                        b_loai,
                        b_so_id,
                        hoadon,
                        hoadon_ct,
                        b_ktra_dch}, this.Fs_SERVICE_NHOperationCompleted, userState);
        }
        
        private void OnFs_SERVICE_NHOperationCompleted(object arg) {
            if ((this.Fs_SERVICE_NHCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Fs_SERVICE_NHCompleted(this, new Fs_SERVICE_NHCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Fs_SERVICE_INVOICE_NH", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Fs_SERVICE_INVOICE_NH(string b_nsd, string b_mk, string b_loai, string b_so_id, string shoadon, string shoadon_ct, string b_ktra_dch) {
            object[] results = this.Invoke("Fs_SERVICE_INVOICE_NH", new object[] {
                        b_nsd,
                        b_mk,
                        b_loai,
                        b_so_id,
                        shoadon,
                        shoadon_ct,
                        b_ktra_dch});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Fs_SERVICE_INVOICE_NHAsync(string b_nsd, string b_mk, string b_loai, string b_so_id, string shoadon, string shoadon_ct, string b_ktra_dch) {
            this.Fs_SERVICE_INVOICE_NHAsync(b_nsd, b_mk, b_loai, b_so_id, shoadon, shoadon_ct, b_ktra_dch, null);
        }
        
        /// <remarks/>
        public void Fs_SERVICE_INVOICE_NHAsync(string b_nsd, string b_mk, string b_loai, string b_so_id, string shoadon, string shoadon_ct, string b_ktra_dch, object userState) {
            if ((this.Fs_SERVICE_INVOICE_NHOperationCompleted == null)) {
                this.Fs_SERVICE_INVOICE_NHOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFs_SERVICE_INVOICE_NHOperationCompleted);
            }
            this.InvokeAsync("Fs_SERVICE_INVOICE_NH", new object[] {
                        b_nsd,
                        b_mk,
                        b_loai,
                        b_so_id,
                        shoadon,
                        shoadon_ct,
                        b_ktra_dch}, this.Fs_SERVICE_INVOICE_NHOperationCompleted, userState);
        }
        
        private void OnFs_SERVICE_INVOICE_NHOperationCompleted(object arg) {
            if ((this.Fs_SERVICE_INVOICE_NHCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Fs_SERVICE_INVOICE_NHCompleted(this, new Fs_SERVICE_INVOICE_NHCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Fs_SERVICE_INVOICE_MUTI_NH", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Fs_SERVICE_INVOICE_MUTI_NH(string b_nsd, string b_mk, string sloai, string shoadon) {
            object[] results = this.Invoke("Fs_SERVICE_INVOICE_MUTI_NH", new object[] {
                        b_nsd,
                        b_mk,
                        sloai,
                        shoadon});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Fs_SERVICE_INVOICE_MUTI_NHAsync(string b_nsd, string b_mk, string sloai, string shoadon) {
            this.Fs_SERVICE_INVOICE_MUTI_NHAsync(b_nsd, b_mk, sloai, shoadon, null);
        }
        
        /// <remarks/>
        public void Fs_SERVICE_INVOICE_MUTI_NHAsync(string b_nsd, string b_mk, string sloai, string shoadon, object userState) {
            if ((this.Fs_SERVICE_INVOICE_MUTI_NHOperationCompleted == null)) {
                this.Fs_SERVICE_INVOICE_MUTI_NHOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFs_SERVICE_INVOICE_MUTI_NHOperationCompleted);
            }
            this.InvokeAsync("Fs_SERVICE_INVOICE_MUTI_NH", new object[] {
                        b_nsd,
                        b_mk,
                        sloai,
                        shoadon}, this.Fs_SERVICE_INVOICE_MUTI_NHOperationCompleted, userState);
        }
        
        private void OnFs_SERVICE_INVOICE_MUTI_NHOperationCompleted(object arg) {
            if ((this.Fs_SERVICE_INVOICE_MUTI_NHCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Fs_SERVICE_INVOICE_MUTI_NHCompleted(this, new Fs_SERVICE_INVOICE_MUTI_NHCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Fs_SERVICE_INVOICE_IN", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Fs_SERVICE_INVOICE_IN(string b_nsd, string b_mk, string b_soid, string loai_in) {
            object[] results = this.Invoke("Fs_SERVICE_INVOICE_IN", new object[] {
                        b_nsd,
                        b_mk,
                        b_soid,
                        loai_in});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Fs_SERVICE_INVOICE_INAsync(string b_nsd, string b_mk, string b_soid, string loai_in) {
            this.Fs_SERVICE_INVOICE_INAsync(b_nsd, b_mk, b_soid, loai_in, null);
        }
        
        /// <remarks/>
        public void Fs_SERVICE_INVOICE_INAsync(string b_nsd, string b_mk, string b_soid, string loai_in, object userState) {
            if ((this.Fs_SERVICE_INVOICE_INOperationCompleted == null)) {
                this.Fs_SERVICE_INVOICE_INOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFs_SERVICE_INVOICE_INOperationCompleted);
            }
            this.InvokeAsync("Fs_SERVICE_INVOICE_IN", new object[] {
                        b_nsd,
                        b_mk,
                        b_soid,
                        loai_in}, this.Fs_SERVICE_INVOICE_INOperationCompleted, userState);
        }
        
        private void OnFs_SERVICE_INVOICE_INOperationCompleted(object arg) {
            if ((this.Fs_SERVICE_INVOICE_INCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Fs_SERVICE_INVOICE_INCompleted(this, new Fs_SERVICE_INVOICE_INCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Fs_SERVICE_INVOICE_IN_FKEY", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Fs_SERVICE_INVOICE_IN_FKEY(string b_nsd, string b_mk, string b_key, string loai_in) {
            object[] results = this.Invoke("Fs_SERVICE_INVOICE_IN_FKEY", new object[] {
                        b_nsd,
                        b_mk,
                        b_key,
                        loai_in});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Fs_SERVICE_INVOICE_IN_FKEYAsync(string b_nsd, string b_mk, string b_key, string loai_in) {
            this.Fs_SERVICE_INVOICE_IN_FKEYAsync(b_nsd, b_mk, b_key, loai_in, null);
        }
        
        /// <remarks/>
        public void Fs_SERVICE_INVOICE_IN_FKEYAsync(string b_nsd, string b_mk, string b_key, string loai_in, object userState) {
            if ((this.Fs_SERVICE_INVOICE_IN_FKEYOperationCompleted == null)) {
                this.Fs_SERVICE_INVOICE_IN_FKEYOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFs_SERVICE_INVOICE_IN_FKEYOperationCompleted);
            }
            this.InvokeAsync("Fs_SERVICE_INVOICE_IN_FKEY", new object[] {
                        b_nsd,
                        b_mk,
                        b_key,
                        loai_in}, this.Fs_SERVICE_INVOICE_IN_FKEYOperationCompleted, userState);
        }
        
        private void OnFs_SERVICE_INVOICE_IN_FKEYOperationCompleted(object arg) {
            if ((this.Fs_SERVICE_INVOICE_IN_FKEYCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Fs_SERVICE_INVOICE_IN_FKEYCompleted(this, new Fs_SERVICE_INVOICE_IN_FKEYCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Fs_SERVICE_INVOICE_HUY", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Fs_SERVICE_INVOICE_HUY(string b_nsd, string b_mk, string b_soid) {
            object[] results = this.Invoke("Fs_SERVICE_INVOICE_HUY", new object[] {
                        b_nsd,
                        b_mk,
                        b_soid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Fs_SERVICE_INVOICE_HUYAsync(string b_nsd, string b_mk, string b_soid) {
            this.Fs_SERVICE_INVOICE_HUYAsync(b_nsd, b_mk, b_soid, null);
        }
        
        /// <remarks/>
        public void Fs_SERVICE_INVOICE_HUYAsync(string b_nsd, string b_mk, string b_soid, object userState) {
            if ((this.Fs_SERVICE_INVOICE_HUYOperationCompleted == null)) {
                this.Fs_SERVICE_INVOICE_HUYOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFs_SERVICE_INVOICE_HUYOperationCompleted);
            }
            this.InvokeAsync("Fs_SERVICE_INVOICE_HUY", new object[] {
                        b_nsd,
                        b_mk,
                        b_soid}, this.Fs_SERVICE_INVOICE_HUYOperationCompleted, userState);
        }
        
        private void OnFs_SERVICE_INVOICE_HUYOperationCompleted(object arg) {
            if ((this.Fs_SERVICE_INVOICE_HUYCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Fs_SERVICE_INVOICE_HUYCompleted(this, new Fs_SERVICE_INVOICE_HUYCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Fs_SERVICE_INVOICE_HUY_FKEY", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Fs_SERVICE_INVOICE_HUY_FKEY(string b_nsd, string b_mk, string b_key) {
            object[] results = this.Invoke("Fs_SERVICE_INVOICE_HUY_FKEY", new object[] {
                        b_nsd,
                        b_mk,
                        b_key});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Fs_SERVICE_INVOICE_HUY_FKEYAsync(string b_nsd, string b_mk, string b_key) {
            this.Fs_SERVICE_INVOICE_HUY_FKEYAsync(b_nsd, b_mk, b_key, null);
        }
        
        /// <remarks/>
        public void Fs_SERVICE_INVOICE_HUY_FKEYAsync(string b_nsd, string b_mk, string b_key, object userState) {
            if ((this.Fs_SERVICE_INVOICE_HUY_FKEYOperationCompleted == null)) {
                this.Fs_SERVICE_INVOICE_HUY_FKEYOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFs_SERVICE_INVOICE_HUY_FKEYOperationCompleted);
            }
            this.InvokeAsync("Fs_SERVICE_INVOICE_HUY_FKEY", new object[] {
                        b_nsd,
                        b_mk,
                        b_key}, this.Fs_SERVICE_INVOICE_HUY_FKEYOperationCompleted, userState);
        }
        
        private void OnFs_SERVICE_INVOICE_HUY_FKEYOperationCompleted(object arg) {
            if ((this.Fs_SERVICE_INVOICE_HUY_FKEYCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Fs_SERVICE_INVOICE_HUY_FKEYCompleted(this, new Fs_SERVICE_INVOICE_HUY_FKEYCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Fs_SERVICE_INVOICE_CT", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Fs_SERVICE_INVOICE_CT(string b_nsd, string b_mk, string b_so_id) {
            object[] results = this.Invoke("Fs_SERVICE_INVOICE_CT", new object[] {
                        b_nsd,
                        b_mk,
                        b_so_id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Fs_SERVICE_INVOICE_CTAsync(string b_nsd, string b_mk, string b_so_id) {
            this.Fs_SERVICE_INVOICE_CTAsync(b_nsd, b_mk, b_so_id, null);
        }
        
        /// <remarks/>
        public void Fs_SERVICE_INVOICE_CTAsync(string b_nsd, string b_mk, string b_so_id, object userState) {
            if ((this.Fs_SERVICE_INVOICE_CTOperationCompleted == null)) {
                this.Fs_SERVICE_INVOICE_CTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFs_SERVICE_INVOICE_CTOperationCompleted);
            }
            this.InvokeAsync("Fs_SERVICE_INVOICE_CT", new object[] {
                        b_nsd,
                        b_mk,
                        b_so_id}, this.Fs_SERVICE_INVOICE_CTOperationCompleted, userState);
        }
        
        private void OnFs_SERVICE_INVOICE_CTOperationCompleted(object arg) {
            if ((this.Fs_SERVICE_INVOICE_CTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Fs_SERVICE_INVOICE_CTCompleted(this, new Fs_SERVICE_INVOICE_CTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Fs_USER_TT", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Fs_USER_TT(string b_ma_login, string b_loai) {
            object[] results = this.Invoke("Fs_USER_TT", new object[] {
                        b_ma_login,
                        b_loai});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Fs_USER_TTAsync(string b_ma_login, string b_loai) {
            this.Fs_USER_TTAsync(b_ma_login, b_loai, null);
        }
        
        /// <remarks/>
        public void Fs_USER_TTAsync(string b_ma_login, string b_loai, object userState) {
            if ((this.Fs_USER_TTOperationCompleted == null)) {
                this.Fs_USER_TTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFs_USER_TTOperationCompleted);
            }
            this.InvokeAsync("Fs_USER_TT", new object[] {
                        b_ma_login,
                        b_loai}, this.Fs_USER_TTOperationCompleted, userState);
        }
        
        private void OnFs_USER_TTOperationCompleted(object arg) {
            if ((this.Fs_USER_TTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Fs_USER_TTCompleted(this, new Fs_USER_TTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Fs_IV_MA_FKEY", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Fs_IV_MA_FKEY(string b_nsd, string b_mk, string b_ma, string b_seri, string b_soc) {
            object[] results = this.Invoke("Fs_IV_MA_FKEY", new object[] {
                        b_nsd,
                        b_mk,
                        b_ma,
                        b_seri,
                        b_soc});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Fs_IV_MA_FKEYAsync(string b_nsd, string b_mk, string b_ma, string b_seri, string b_soc) {
            this.Fs_IV_MA_FKEYAsync(b_nsd, b_mk, b_ma, b_seri, b_soc, null);
        }
        
        /// <remarks/>
        public void Fs_IV_MA_FKEYAsync(string b_nsd, string b_mk, string b_ma, string b_seri, string b_soc, object userState) {
            if ((this.Fs_IV_MA_FKEYOperationCompleted == null)) {
                this.Fs_IV_MA_FKEYOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFs_IV_MA_FKEYOperationCompleted);
            }
            this.InvokeAsync("Fs_IV_MA_FKEY", new object[] {
                        b_nsd,
                        b_mk,
                        b_ma,
                        b_seri,
                        b_soc}, this.Fs_IV_MA_FKEYOperationCompleted, userState);
        }
        
        private void OnFs_IV_MA_FKEYOperationCompleted(object arg) {
            if ((this.Fs_IV_MA_FKEYCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Fs_IV_MA_FKEYCompleted(this, new Fs_IV_MA_FKEYCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Fs_SERVICE_INVOICE_KEY_CT", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Fs_SERVICE_INVOICE_KEY_CT(string b_nsd, string b_mk, string b_key) {
            object[] results = this.Invoke("Fs_SERVICE_INVOICE_KEY_CT", new object[] {
                        b_nsd,
                        b_mk,
                        b_key});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Fs_SERVICE_INVOICE_KEY_CTAsync(string b_nsd, string b_mk, string b_key) {
            this.Fs_SERVICE_INVOICE_KEY_CTAsync(b_nsd, b_mk, b_key, null);
        }
        
        /// <remarks/>
        public void Fs_SERVICE_INVOICE_KEY_CTAsync(string b_nsd, string b_mk, string b_key, object userState) {
            if ((this.Fs_SERVICE_INVOICE_KEY_CTOperationCompleted == null)) {
                this.Fs_SERVICE_INVOICE_KEY_CTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFs_SERVICE_INVOICE_KEY_CTOperationCompleted);
            }
            this.InvokeAsync("Fs_SERVICE_INVOICE_KEY_CT", new object[] {
                        b_nsd,
                        b_mk,
                        b_key}, this.Fs_SERVICE_INVOICE_KEY_CTOperationCompleted, userState);
        }
        
        private void OnFs_SERVICE_INVOICE_KEY_CTOperationCompleted(object arg) {
            if ((this.Fs_SERVICE_INVOICE_KEY_CTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Fs_SERVICE_INVOICE_KEY_CTCompleted(this, new Fs_SERVICE_INVOICE_KEY_CTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Fs_SERVICE_INVOICE_KEY_CT_XML", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Fs_SERVICE_INVOICE_KEY_CT_XML(string b_nsd, string b_mk, string b_key) {
            object[] results = this.Invoke("Fs_SERVICE_INVOICE_KEY_CT_XML", new object[] {
                        b_nsd,
                        b_mk,
                        b_key});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Fs_SERVICE_INVOICE_KEY_CT_XMLAsync(string b_nsd, string b_mk, string b_key) {
            this.Fs_SERVICE_INVOICE_KEY_CT_XMLAsync(b_nsd, b_mk, b_key, null);
        }
        
        /// <remarks/>
        public void Fs_SERVICE_INVOICE_KEY_CT_XMLAsync(string b_nsd, string b_mk, string b_key, object userState) {
            if ((this.Fs_SERVICE_INVOICE_KEY_CT_XMLOperationCompleted == null)) {
                this.Fs_SERVICE_INVOICE_KEY_CT_XMLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFs_SERVICE_INVOICE_KEY_CT_XMLOperationCompleted);
            }
            this.InvokeAsync("Fs_SERVICE_INVOICE_KEY_CT_XML", new object[] {
                        b_nsd,
                        b_mk,
                        b_key}, this.Fs_SERVICE_INVOICE_KEY_CT_XMLOperationCompleted, userState);
        }
        
        private void OnFs_SERVICE_INVOICE_KEY_CT_XMLOperationCompleted(object arg) {
            if ((this.Fs_SERVICE_INVOICE_KEY_CT_XMLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Fs_SERVICE_INVOICE_KEY_CT_XMLCompleted(this, new Fs_SERVICE_INVOICE_KEY_CT_XMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Fs_SERVICE_IMPORT_DENSO", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Fs_SERVICE_IMPORT_DENSO(string b_nsd, string b_mk, string sloai, string sma, string skyhieu, string shoadon) {
            object[] results = this.Invoke("Fs_SERVICE_IMPORT_DENSO", new object[] {
                        b_nsd,
                        b_mk,
                        sloai,
                        sma,
                        skyhieu,
                        shoadon});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Fs_SERVICE_IMPORT_DENSOAsync(string b_nsd, string b_mk, string sloai, string sma, string skyhieu, string shoadon) {
            this.Fs_SERVICE_IMPORT_DENSOAsync(b_nsd, b_mk, sloai, sma, skyhieu, shoadon, null);
        }
        
        /// <remarks/>
        public void Fs_SERVICE_IMPORT_DENSOAsync(string b_nsd, string b_mk, string sloai, string sma, string skyhieu, string shoadon, object userState) {
            if ((this.Fs_SERVICE_IMPORT_DENSOOperationCompleted == null)) {
                this.Fs_SERVICE_IMPORT_DENSOOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFs_SERVICE_IMPORT_DENSOOperationCompleted);
            }
            this.InvokeAsync("Fs_SERVICE_IMPORT_DENSO", new object[] {
                        b_nsd,
                        b_mk,
                        sloai,
                        sma,
                        skyhieu,
                        shoadon}, this.Fs_SERVICE_IMPORT_DENSOOperationCompleted, userState);
        }
        
        private void OnFs_SERVICE_IMPORT_DENSOOperationCompleted(object arg) {
            if ((this.Fs_SERVICE_IMPORT_DENSOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Fs_SERVICE_IMPORT_DENSOCompleted(this, new Fs_SERVICE_IMPORT_DENSOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Fs_LoadListMau", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Fs_LoadListMau(string b_nsd, string b_mk, string sloai) {
            object[] results = this.Invoke("Fs_LoadListMau", new object[] {
                        b_nsd,
                        b_mk,
                        sloai});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Fs_LoadListMauAsync(string b_nsd, string b_mk, string sloai) {
            this.Fs_LoadListMauAsync(b_nsd, b_mk, sloai, null);
        }
        
        /// <remarks/>
        public void Fs_LoadListMauAsync(string b_nsd, string b_mk, string sloai, object userState) {
            if ((this.Fs_LoadListMauOperationCompleted == null)) {
                this.Fs_LoadListMauOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFs_LoadListMauOperationCompleted);
            }
            this.InvokeAsync("Fs_LoadListMau", new object[] {
                        b_nsd,
                        b_mk,
                        sloai}, this.Fs_LoadListMauOperationCompleted, userState);
        }
        
        private void OnFs_LoadListMauOperationCompleted(object arg) {
            if ((this.Fs_LoadListMauCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Fs_LoadListMauCompleted(this, new Fs_LoadListMauCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Fs_LoadListSeri", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Fs_LoadListSeri(string b_nsd, string b_mk, string sMau) {
            object[] results = this.Invoke("Fs_LoadListSeri", new object[] {
                        b_nsd,
                        b_mk,
                        sMau});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Fs_LoadListSeriAsync(string b_nsd, string b_mk, string sMau) {
            this.Fs_LoadListSeriAsync(b_nsd, b_mk, sMau, null);
        }
        
        /// <remarks/>
        public void Fs_LoadListSeriAsync(string b_nsd, string b_mk, string sMau, object userState) {
            if ((this.Fs_LoadListSeriOperationCompleted == null)) {
                this.Fs_LoadListSeriOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFs_LoadListSeriOperationCompleted);
            }
            this.InvokeAsync("Fs_LoadListSeri", new object[] {
                        b_nsd,
                        b_mk,
                        sMau}, this.Fs_LoadListSeriOperationCompleted, userState);
        }
        
        private void OnFs_LoadListSeriOperationCompleted(object arg) {
            if ((this.Fs_LoadListSeriCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Fs_LoadListSeriCompleted(this, new Fs_LoadListSeriCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Fs_SERVICE_KY_SERVER", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Fs_SERVICE_KY_SERVER(string b_nsd, string b_mk, string b_so_id) {
            object[] results = this.Invoke("Fs_SERVICE_KY_SERVER", new object[] {
                        b_nsd,
                        b_mk,
                        b_so_id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Fs_SERVICE_KY_SERVERAsync(string b_nsd, string b_mk, string b_so_id) {
            this.Fs_SERVICE_KY_SERVERAsync(b_nsd, b_mk, b_so_id, null);
        }
        
        /// <remarks/>
        public void Fs_SERVICE_KY_SERVERAsync(string b_nsd, string b_mk, string b_so_id, object userState) {
            if ((this.Fs_SERVICE_KY_SERVEROperationCompleted == null)) {
                this.Fs_SERVICE_KY_SERVEROperationCompleted = new System.Threading.SendOrPostCallback(this.OnFs_SERVICE_KY_SERVEROperationCompleted);
            }
            this.InvokeAsync("Fs_SERVICE_KY_SERVER", new object[] {
                        b_nsd,
                        b_mk,
                        b_so_id}, this.Fs_SERVICE_KY_SERVEROperationCompleted, userState);
        }
        
        private void OnFs_SERVICE_KY_SERVEROperationCompleted(object arg) {
            if ((this.Fs_SERVICE_KY_SERVERCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Fs_SERVICE_KY_SERVERCompleted(this, new Fs_SERVICE_KY_SERVERCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Fs_SERVICE_KY_MUTIL_SERVER", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Fs_SERVICE_KY_MUTIL_SERVER(string b_nsd, string b_mk, string b_chuoi_so_id) {
            object[] results = this.Invoke("Fs_SERVICE_KY_MUTIL_SERVER", new object[] {
                        b_nsd,
                        b_mk,
                        b_chuoi_so_id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Fs_SERVICE_KY_MUTIL_SERVERAsync(string b_nsd, string b_mk, string b_chuoi_so_id) {
            this.Fs_SERVICE_KY_MUTIL_SERVERAsync(b_nsd, b_mk, b_chuoi_so_id, null);
        }
        
        /// <remarks/>
        public void Fs_SERVICE_KY_MUTIL_SERVERAsync(string b_nsd, string b_mk, string b_chuoi_so_id, object userState) {
            if ((this.Fs_SERVICE_KY_MUTIL_SERVEROperationCompleted == null)) {
                this.Fs_SERVICE_KY_MUTIL_SERVEROperationCompleted = new System.Threading.SendOrPostCallback(this.OnFs_SERVICE_KY_MUTIL_SERVEROperationCompleted);
            }
            this.InvokeAsync("Fs_SERVICE_KY_MUTIL_SERVER", new object[] {
                        b_nsd,
                        b_mk,
                        b_chuoi_so_id}, this.Fs_SERVICE_KY_MUTIL_SERVEROperationCompleted, userState);
        }
        
        private void OnFs_SERVICE_KY_MUTIL_SERVEROperationCompleted(object arg) {
            if ((this.Fs_SERVICE_KY_MUTIL_SERVERCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Fs_SERVICE_KY_MUTIL_SERVERCompleted(this, new Fs_SERVICE_KY_MUTIL_SERVERCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Fs_DN_CT", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Fs_DN_CT(string b_nsd, string b_mk, string b_tax) {
            object[] results = this.Invoke("Fs_DN_CT", new object[] {
                        b_nsd,
                        b_mk,
                        b_tax});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Fs_DN_CTAsync(string b_nsd, string b_mk, string b_tax) {
            this.Fs_DN_CTAsync(b_nsd, b_mk, b_tax, null);
        }
        
        /// <remarks/>
        public void Fs_DN_CTAsync(string b_nsd, string b_mk, string b_tax, object userState) {
            if ((this.Fs_DN_CTOperationCompleted == null)) {
                this.Fs_DN_CTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFs_DN_CTOperationCompleted);
            }
            this.InvokeAsync("Fs_DN_CT", new object[] {
                        b_nsd,
                        b_mk,
                        b_tax}, this.Fs_DN_CTOperationCompleted, userState);
        }
        
        private void OnFs_DN_CTOperationCompleted(object arg) {
            if ((this.Fs_DN_CTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Fs_DN_CTCompleted(this, new Fs_DN_CTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TOOL_SENDMAIL", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TOOL_SENDMAIL() {
            object[] results = this.Invoke("TOOL_SENDMAIL", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TOOL_SENDMAILAsync() {
            this.TOOL_SENDMAILAsync(null);
        }
        
        /// <remarks/>
        public void TOOL_SENDMAILAsync(object userState) {
            if ((this.TOOL_SENDMAILOperationCompleted == null)) {
                this.TOOL_SENDMAILOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTOOL_SENDMAILOperationCompleted);
            }
            this.InvokeAsync("TOOL_SENDMAIL", new object[0], this.TOOL_SENDMAILOperationCompleted, userState);
        }
        
        private void OnTOOL_SENDMAILOperationCompleted(object arg) {
            if ((this.TOOL_SENDMAILCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TOOL_SENDMAILCompleted(this, new TOOL_SENDMAILCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class hoadon_gtgt {
        
        private string keyField;
        
        private string linktracuuField;
        
        private string maField;
        
        private string ng_hdField;
        
        private string seriField;
        
        private string ma_nthueField;
        
        private string kieu_soField;
        
        private string ma_khField;
        
        private string tenField;
        
        private string phoneField;
        
        private string taxField;
        
        private string dchiField;
        
        private string ma_tkField;
        
        private string ten_nhField;
        
        private string mailHField;
        
        private string phoneHField;
        
        private string tenMField;
        
        private string ma_khLField;
        
        private string ma_ntField;
        
        private double tgField;
        
        private string hthucField;
        
        private string hanField;
        
        private string tl_ggiaField;
        
        private string ggiaField;
        
        private string phiField;
        
        private string noidungField;
        
        private string tienField;
        
        private string ttoanField;
        
        private string ptien_vcField;
        
        private string quayField;
        
        private string ten_quayField;
        
        private string hinhthuc_guiField;
        
        private hoadon_gtgt_ct[] hoadon_gtgt_ctField;
        
        /// <remarks/>
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string linktracuu {
            get {
                return this.linktracuuField;
            }
            set {
                this.linktracuuField = value;
            }
        }
        
        /// <remarks/>
        public string ma {
            get {
                return this.maField;
            }
            set {
                this.maField = value;
            }
        }
        
        /// <remarks/>
        public string ng_hd {
            get {
                return this.ng_hdField;
            }
            set {
                this.ng_hdField = value;
            }
        }
        
        /// <remarks/>
        public string seri {
            get {
                return this.seriField;
            }
            set {
                this.seriField = value;
            }
        }
        
        /// <remarks/>
        public string ma_nthue {
            get {
                return this.ma_nthueField;
            }
            set {
                this.ma_nthueField = value;
            }
        }
        
        /// <remarks/>
        public string kieu_so {
            get {
                return this.kieu_soField;
            }
            set {
                this.kieu_soField = value;
            }
        }
        
        /// <remarks/>
        public string ma_kh {
            get {
                return this.ma_khField;
            }
            set {
                this.ma_khField = value;
            }
        }
        
        /// <remarks/>
        public string ten {
            get {
                return this.tenField;
            }
            set {
                this.tenField = value;
            }
        }
        
        /// <remarks/>
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public string tax {
            get {
                return this.taxField;
            }
            set {
                this.taxField = value;
            }
        }
        
        /// <remarks/>
        public string dchi {
            get {
                return this.dchiField;
            }
            set {
                this.dchiField = value;
            }
        }
        
        /// <remarks/>
        public string ma_tk {
            get {
                return this.ma_tkField;
            }
            set {
                this.ma_tkField = value;
            }
        }
        
        /// <remarks/>
        public string ten_nh {
            get {
                return this.ten_nhField;
            }
            set {
                this.ten_nhField = value;
            }
        }
        
        /// <remarks/>
        public string mailH {
            get {
                return this.mailHField;
            }
            set {
                this.mailHField = value;
            }
        }
        
        /// <remarks/>
        public string phoneH {
            get {
                return this.phoneHField;
            }
            set {
                this.phoneHField = value;
            }
        }
        
        /// <remarks/>
        public string tenM {
            get {
                return this.tenMField;
            }
            set {
                this.tenMField = value;
            }
        }
        
        /// <remarks/>
        public string ma_khL {
            get {
                return this.ma_khLField;
            }
            set {
                this.ma_khLField = value;
            }
        }
        
        /// <remarks/>
        public string ma_nt {
            get {
                return this.ma_ntField;
            }
            set {
                this.ma_ntField = value;
            }
        }
        
        /// <remarks/>
        public double tg {
            get {
                return this.tgField;
            }
            set {
                this.tgField = value;
            }
        }
        
        /// <remarks/>
        public string hthuc {
            get {
                return this.hthucField;
            }
            set {
                this.hthucField = value;
            }
        }
        
        /// <remarks/>
        public string han {
            get {
                return this.hanField;
            }
            set {
                this.hanField = value;
            }
        }
        
        /// <remarks/>
        public string tl_ggia {
            get {
                return this.tl_ggiaField;
            }
            set {
                this.tl_ggiaField = value;
            }
        }
        
        /// <remarks/>
        public string ggia {
            get {
                return this.ggiaField;
            }
            set {
                this.ggiaField = value;
            }
        }
        
        /// <remarks/>
        public string phi {
            get {
                return this.phiField;
            }
            set {
                this.phiField = value;
            }
        }
        
        /// <remarks/>
        public string noidung {
            get {
                return this.noidungField;
            }
            set {
                this.noidungField = value;
            }
        }
        
        /// <remarks/>
        public string tien {
            get {
                return this.tienField;
            }
            set {
                this.tienField = value;
            }
        }
        
        /// <remarks/>
        public string ttoan {
            get {
                return this.ttoanField;
            }
            set {
                this.ttoanField = value;
            }
        }
        
        /// <remarks/>
        public string ptien_vc {
            get {
                return this.ptien_vcField;
            }
            set {
                this.ptien_vcField = value;
            }
        }
        
        /// <remarks/>
        public string quay {
            get {
                return this.quayField;
            }
            set {
                this.quayField = value;
            }
        }
        
        /// <remarks/>
        public string ten_quay {
            get {
                return this.ten_quayField;
            }
            set {
                this.ten_quayField = value;
            }
        }
        
        /// <remarks/>
        public string hinhthuc_gui {
            get {
                return this.hinhthuc_guiField;
            }
            set {
                this.hinhthuc_guiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("hoadon_gtgt_ct")]
        public hoadon_gtgt_ct[] hoadon_gtgt_ct {
            get {
                return this.hoadon_gtgt_ctField;
            }
            set {
                this.hoadon_gtgt_ctField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class hoadon_gtgt_ct {
        
        private string ma_vtField;
        
        private string tENField;
        
        private string dvtField;
        
        private string luongField;
        
        private string giaField;
        
        private string tienField;
        
        private string tsField;
        
        private string thueField;
        
        private string ttoanField;
        
        private string them1Field;
        
        private string them2Field;
        
        private string them3Field;
        
        private string ndField;
        
        private string tl_ckField;
        
        private string tien_ckField;
        
        private string tuoivangField;
        
        private string trongluongField;
        
        private string tiencongField;
        
        private string ma_barcodeField;
        
        /// <remarks/>
        public string ma_vt {
            get {
                return this.ma_vtField;
            }
            set {
                this.ma_vtField = value;
            }
        }
        
        /// <remarks/>
        public string TEN {
            get {
                return this.tENField;
            }
            set {
                this.tENField = value;
            }
        }
        
        /// <remarks/>
        public string dvt {
            get {
                return this.dvtField;
            }
            set {
                this.dvtField = value;
            }
        }
        
        /// <remarks/>
        public string luong {
            get {
                return this.luongField;
            }
            set {
                this.luongField = value;
            }
        }
        
        /// <remarks/>
        public string gia {
            get {
                return this.giaField;
            }
            set {
                this.giaField = value;
            }
        }
        
        /// <remarks/>
        public string tien {
            get {
                return this.tienField;
            }
            set {
                this.tienField = value;
            }
        }
        
        /// <remarks/>
        public string ts {
            get {
                return this.tsField;
            }
            set {
                this.tsField = value;
            }
        }
        
        /// <remarks/>
        public string thue {
            get {
                return this.thueField;
            }
            set {
                this.thueField = value;
            }
        }
        
        /// <remarks/>
        public string ttoan {
            get {
                return this.ttoanField;
            }
            set {
                this.ttoanField = value;
            }
        }
        
        /// <remarks/>
        public string them1 {
            get {
                return this.them1Field;
            }
            set {
                this.them1Field = value;
            }
        }
        
        /// <remarks/>
        public string them2 {
            get {
                return this.them2Field;
            }
            set {
                this.them2Field = value;
            }
        }
        
        /// <remarks/>
        public string them3 {
            get {
                return this.them3Field;
            }
            set {
                this.them3Field = value;
            }
        }
        
        /// <remarks/>
        public string nd {
            get {
                return this.ndField;
            }
            set {
                this.ndField = value;
            }
        }
        
        /// <remarks/>
        public string tl_ck {
            get {
                return this.tl_ckField;
            }
            set {
                this.tl_ckField = value;
            }
        }
        
        /// <remarks/>
        public string tien_ck {
            get {
                return this.tien_ckField;
            }
            set {
                this.tien_ckField = value;
            }
        }
        
        /// <remarks/>
        public string tuoivang {
            get {
                return this.tuoivangField;
            }
            set {
                this.tuoivangField = value;
            }
        }
        
        /// <remarks/>
        public string trongluong {
            get {
                return this.trongluongField;
            }
            set {
                this.trongluongField = value;
            }
        }
        
        /// <remarks/>
        public string tiencong {
            get {
                return this.tiencongField;
            }
            set {
                this.tiencongField = value;
            }
        }
        
        /// <remarks/>
        public string ma_barcode {
            get {
                return this.ma_barcodeField;
            }
            set {
                this.ma_barcodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void Fs_SERVICE_HD_NHCompletedEventHandler(object sender, Fs_SERVICE_HD_NHCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Fs_SERVICE_HD_NHCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Fs_SERVICE_HD_NHCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void Fs_IV_MAP_NHCompletedEventHandler(object sender, Fs_IV_MAP_NHCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Fs_IV_MAP_NHCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Fs_IV_MAP_NHCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void Fs_SERVICE_NH_KYCompletedEventHandler(object sender, Fs_SERVICE_NH_KYCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Fs_SERVICE_NH_KYCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Fs_SERVICE_NH_KYCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void Fs_SERVICE_NHCompletedEventHandler(object sender, Fs_SERVICE_NHCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Fs_SERVICE_NHCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Fs_SERVICE_NHCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void Fs_SERVICE_INVOICE_NHCompletedEventHandler(object sender, Fs_SERVICE_INVOICE_NHCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Fs_SERVICE_INVOICE_NHCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Fs_SERVICE_INVOICE_NHCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void Fs_SERVICE_INVOICE_MUTI_NHCompletedEventHandler(object sender, Fs_SERVICE_INVOICE_MUTI_NHCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Fs_SERVICE_INVOICE_MUTI_NHCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Fs_SERVICE_INVOICE_MUTI_NHCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void Fs_SERVICE_INVOICE_INCompletedEventHandler(object sender, Fs_SERVICE_INVOICE_INCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Fs_SERVICE_INVOICE_INCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Fs_SERVICE_INVOICE_INCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void Fs_SERVICE_INVOICE_IN_FKEYCompletedEventHandler(object sender, Fs_SERVICE_INVOICE_IN_FKEYCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Fs_SERVICE_INVOICE_IN_FKEYCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Fs_SERVICE_INVOICE_IN_FKEYCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void Fs_SERVICE_INVOICE_HUYCompletedEventHandler(object sender, Fs_SERVICE_INVOICE_HUYCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Fs_SERVICE_INVOICE_HUYCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Fs_SERVICE_INVOICE_HUYCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void Fs_SERVICE_INVOICE_HUY_FKEYCompletedEventHandler(object sender, Fs_SERVICE_INVOICE_HUY_FKEYCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Fs_SERVICE_INVOICE_HUY_FKEYCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Fs_SERVICE_INVOICE_HUY_FKEYCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void Fs_SERVICE_INVOICE_CTCompletedEventHandler(object sender, Fs_SERVICE_INVOICE_CTCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Fs_SERVICE_INVOICE_CTCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Fs_SERVICE_INVOICE_CTCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void Fs_USER_TTCompletedEventHandler(object sender, Fs_USER_TTCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Fs_USER_TTCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Fs_USER_TTCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void Fs_IV_MA_FKEYCompletedEventHandler(object sender, Fs_IV_MA_FKEYCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Fs_IV_MA_FKEYCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Fs_IV_MA_FKEYCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void Fs_SERVICE_INVOICE_KEY_CTCompletedEventHandler(object sender, Fs_SERVICE_INVOICE_KEY_CTCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Fs_SERVICE_INVOICE_KEY_CTCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Fs_SERVICE_INVOICE_KEY_CTCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void Fs_SERVICE_INVOICE_KEY_CT_XMLCompletedEventHandler(object sender, Fs_SERVICE_INVOICE_KEY_CT_XMLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Fs_SERVICE_INVOICE_KEY_CT_XMLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Fs_SERVICE_INVOICE_KEY_CT_XMLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void Fs_SERVICE_IMPORT_DENSOCompletedEventHandler(object sender, Fs_SERVICE_IMPORT_DENSOCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Fs_SERVICE_IMPORT_DENSOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Fs_SERVICE_IMPORT_DENSOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void Fs_LoadListMauCompletedEventHandler(object sender, Fs_LoadListMauCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Fs_LoadListMauCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Fs_LoadListMauCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void Fs_LoadListSeriCompletedEventHandler(object sender, Fs_LoadListSeriCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Fs_LoadListSeriCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Fs_LoadListSeriCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void Fs_SERVICE_KY_SERVERCompletedEventHandler(object sender, Fs_SERVICE_KY_SERVERCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Fs_SERVICE_KY_SERVERCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Fs_SERVICE_KY_SERVERCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void Fs_SERVICE_KY_MUTIL_SERVERCompletedEventHandler(object sender, Fs_SERVICE_KY_MUTIL_SERVERCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Fs_SERVICE_KY_MUTIL_SERVERCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Fs_SERVICE_KY_MUTIL_SERVERCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void Fs_DN_CTCompletedEventHandler(object sender, Fs_DN_CTCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Fs_DN_CTCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Fs_DN_CTCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void TOOL_SENDMAILCompletedEventHandler(object sender, TOOL_SENDMAILCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TOOL_SENDMAILCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TOOL_SENDMAILCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591